# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Admin.create email: "saju@admin.com", password: "admin123"

About.create main_title: "COLÓQUIO", content: <<-TXT
      <p>A realiza&ccedil;&atilde;o do evento &ldquo;Col&oacute;quio Internacional de Justi&ccedil;a Juvenil na Contemporaneidade&rdquo;, no ano de 2014, resultou em uma experi&ecirc;ncia extremamente positiva no campo da socioeduca&ccedil;&atilde;o, tanto em rela&ccedil;&atilde;o &agrave;s pr&aacute;ticas profissionais, bem como na discuss&atilde;o acad&ecirc;mica.</p>\r\n\r\n
      <p>A partir dos debates e das trocas realizadas no &acirc;mbito do evento, foi poss&iacute;vel estender a interlocu&ccedil;&atilde;o entre quem vivencia, estuda ou trabalha com a tem&aacute;tica. Observamos que agentes universit&aacute;rios(as), t&eacute;cnicos(as) e professores(as) t&ecirc;m se constitu&iacute;do em importantes interlocutores e interlocutoras junto &agrave;s pessoas que operam o sistema socioeducativo, tornando-se, muitas vezes, refer&ecirc;ncia t&eacute;cnica na &aacute;rea.</p>\r\n\r\n
      <p>Todavia, h&aacute; uma necessidade de di&aacute;logo mais aprofundado entre quem trabalha cotidianamente com essa tem&aacute;tica, a qual constitui uma importante pauta pol&iacute;tica e &eacute; cotidianamente veiculada pelos meios midi&aacute;ticos e aqueles que a pesquisam e estudam. No entanto, sua abordagem ainda &eacute; bastante superficial, e n&atilde;o contempla a devida profundidade. Ainda h&aacute; muito a ser feito e discutido no campo da justi&ccedil;a juvenil.</p>\r\n\r\n
      <p>Portanto, a partir do projeto &ldquo;Col&oacute;quio Vivo&rdquo;, pretendemos seguir aprofundando o debate sobre a tem&aacute;tica e os desafios contempor&acirc;neos que envolvem a justi&ccedil;a juvenil. Por meio de trocas, experi&ecirc;ncias, debates e contribui&ccedil;&otilde;es, pretendemos, ao fim deste ciclo, disponibilizar &agrave; comunidade o resultado de trabalho desenvolvido nos encontros.</p>\r\n\r\n
      <p>Nosso p&uacute;blico-alvo abrange profissionais do Sistema Socioeducativo do Rio Grande do Sul, estudantes de Direito, Psicologia, Educa&ccedil;&atilde;o, Servi&ccedil;o Social, e todas as demais pessoas que, de alguma forma, se identifiquem com o objeto de discuss&atilde;o. Al&eacute;m de professores e de professoras universit&aacute;rias e da rede p&uacute;blica.</p>\r\n
  TXT

meeting_one_speakers = Speaker.create!([
    {name: "Carmem Maria Craidy", profile: "http://lattes.cnpq.br/3011518752311970", description: "Doutora em Educação, professora na Universidade Federal do Rio Grande do Sul e conselheira do Conselho Estadual de Educação do Estado do Rio Grande do Sul"},
    {name: "Vera Ponzio", profile: "", description: "Socióloga e Coordenadora do CREAS (Centro de Referencia Especializado de Assistência Social) Partenon"}
])

meeting_two_speakers = Speaker.create!([
    {name: "Fernanda Amador", profile: "http://lattes.cnpq.br/4367961141610735", description: "Professora do Departamento de Psicologia Social e Institucional do Instituto de Psicologia da UFRGS e líder do Grupo de Pesquisa N-PISTA(s) - Núcleo de Pesquisas em Instituições, Subjetivação e Trabalho em Análise(s)"},
    {name: "Miriam Gomes Burger", profile: "", description: "Psicóloga com formação na APPOA, experiência na área social tendo trabalhado na FASC e na FASE"}
])
meeting_three_speakers = Speaker.create!([
      {name: "Dalmir Franklin de Oliveira Junior", profile: "http://lattes.cnpq.br/7781532356800258", description: "Juiz de Direito no Juizado Regional da Infância e Juventude da Comarca de Passo Fundo"},
      {name: "Giancarlo Silkunas Vay", profile: "http://lattes.cnpq.br/3053232275125840", description: "Defensor Público do estado de São Paulo e membro do núcleo especializado da infância e juventude da DPESP (Defensoria Pública do estado de São Paulo)"}
])

meeting_four_speaker = Speaker.create!([
  {name: "Alba Maria Zaluar", profile: "http://lattes.cnpq.br/0220993427804509", description: "Antropóloga brasileira, com atuação na área de antropologia urbana e antropologia da violência. Professora aposentada do  Instituto de Medicina Social da Universidade do Estado do Rio de Janeiro, onde fundou e coordenou o Núcleo de Pesquisa em Violências (NUPEVI). Professora  visitante no Instituto de Estudos Sociais e Políticos/UERJ."}
])

Meeting.create!([
  {title: "PROCESSO PENAL JUVENIL: QUANDO A PRÁTICA OCUPA O VAZIO DA LEI", body: '<p>A efetiva defesa de adolescentes envolvidos em atos infracionais perpassa impreterivelmente a defesa por um processo penal juvenil democrático. Apesar do Estatuto da Criança e do Adolescente trazer em seu bojo a Doutrina da Proteção Integral, o dispositivo não instrumentalizou formas de garantir a efetiva aplicação desta nova concepção. Uma vez que existem diversas lacunas no ECA, a hermenêutica que busca supri-las, por meio da aplicação dos operadores jurídicos, se mostra de uma ampla diversidade, refletindo diferentes concepções do que consiste, afinal, a Proteção Integral. A adoção do sistema recursal civil frente a uma matéria que muito se aproxima do domínio penal, e uma intervenção jurídica de natureza ainda não solidificada dificultam a realização de um processo penal juvenil legítimo. A experiência tem revelado a existência de práticas que não coadunam com os direitos dos adolescentes estabelecidos pelo ECA. Sem um processo penal juvenil que garanta efetivamente a ampla defesa e o contraditório, a medida aplicada ao adolescente perde a pertinência. O objetivo deste painel é discutir a atuação judicial na temática, situando os participantes do Colóquio quanto aos problemas vivenciados na prática da Justiça da infância e da Juventude. Por fim, lança-se o desafio de constituir caminhos alternativos na direção de uma defesa processual efetiva.</p>', venue: "                Sala 102 da FACED <br/>\r\n                (Av. Paulo Gama s/n - Prédio 12201 térreo <br/>\r\n                Bairro Farroupilha - Porto Alegre. CEP: 90046-900) <br/>\r\n", date: "2015-06-08", start_time: "2000-01-01 18:30:00",
  speakers: meeting_three_speakers },
  {title: "QUEM CUIDA DA SAÚDE DE QUEM TRABALHA NA SOCIOEDUCAÇÃO?", body: "<p>O número de pessoas que trabalham no Sistema Nacional de Atendimento Socioeducativo - SINASE tem aumentado em todo o território nacional a cada ano, tanto na esfera da gestão das instituições quanto na execução da política. Segundo Costa et al (2014), não é possível executar medidas socioeducativas, de acordo com o conteúdo normativo do SINASE, sem contar com recursos humanos, preparados, envolvidos e motivados para essa tarefa, que traz conteúdos que afetam diretamente a subjetividade do trabalhador. O SINASE enquanto política pública tem se tornado uma área de prestação de serviços cuja mediação principal é o(a) próprio(a) trabalhador(a), ele(a) é a sua principal tecnologia, e por isso o trabalho exige, além de novas formas de regulação, organização e gestão, que se olhe e se cuide desse público alvo. Nossa proposta para esse encontro é problematizar e debater como estamos assumindo o desafio de cuidar de quem trabalha na socioeducação.</p>", venue: "<p>Sala 102 da FACED <br/>\r\n      (Av. Paulo Gama s/n - Prédio 12201 térreo <br/>\r\n      Bairro Farroupilha - Porto Alegre. CEP: 90046-900)<br/>\r\n</p>", date: "2015-05-25", start_time: "2000-01-01 18:30:00",
  speakers: meeting_two_speakers },
  {title: "IDENTIDADE MASCULINA E VIOLÊNCIA: DISCUTINDO GÊNERO NA MORTALIDADE JUVENIL", body: "<p>De acordo com a perspectiva e estudo sobre as quest&otilde;es de g&ecirc;nero, mulheres e homens vivem, exercem e percebem a viol&ecirc;ncia e a inseguran&ccedil;a de maneira diferente, assim como seu impacto &eacute; diferente em um ou outro g&ecirc;nero. Diversos estudos apontam que a taxa de homic&iacute;dios de v&iacute;timas do sexo masculino com idades ente 15 e 29 anos na Am&eacute;rica do Sul &eacute; uma das maiores do mundo. Pode-se considerar que a concentra&ccedil;&atilde;o de viol&ecirc;ncia neste grupo est&aacute; relacionada com a preval&ecirc;ncia de padr&otilde;es socioculturais, formas de socializa&ccedil;&atilde;o e identifica&ccedil;&atilde;o subjetivantes que contribuem para que valores como o respeito, a dignidade e o reconhecimento dos pares estejam associados, na pr&aacute;tica, com a disposi&ccedil;&atilde;o a adotar condutas e formas de conviv&ecirc;ncia violentas. Por tal motivo, buscamos, neste encontro, problematizar a constru&ccedil;&atilde;o social de masculinidades permeadas pela viol&ecirc;ncia, na tentativa de auxiliar a compreens&atilde;o das implica&ccedil;&otilde;es de tal fen&ocirc;meno nas vidas/experi&ecirc;ncias de adolescentes em conflito com a lei.</p>\r\n", venue: "              <p>\r\n                Sala 102 da FACED <br/>\r\n                (Av. Paulo Gama s/n - Prédio 12201 térreo <br/>\r\n                Bairro Farroupilha - Porto Alegre. CEP: 90046-900) <br/>\r\n              </p>\r\n", date: "2015-07-06", start_time: "2000-01-01 18:30:00",
  speakers: meeting_four_speaker },
  {title: "MEDIDAS SOCIOEDUCATIVAS EM MEIO ABERTO: O EXERCÍCIO DA RESPONSABILIZAÇÃO COM LIBERDADE",
    body: '<p>A discussão sobre medida socioeducativa no Rio Grande do Sul e no Brasil não apresenta uma uniformidade no que diz respeito ao seu lugar de educação, socialização e responsabilização. Observamos que a expectativa sobre a punição de quem se encontra “em Conflito com a Lei“, para a sociedade de um modo geral, sempre foi de que o castigo infringido ao(à) criminoso(a) – no caso de adolescentes, aqueles(as) que praticam ato infracional - fosse suficientemente grande e severo a ponto de fazer cessar a reincidência. A proposição de um sistema de responsabilização que prioriza a pessoa em detrimento do ato infracional, representa a grande diferença entre o Código Penal e o que prevê o Estatuto da Criança e do Adolescente. Há um contraponto que se efetiva na medida socioeducativa de meio aberto por não se tratar de uma pessoa isolado que deverá responder sozinha por sua conduta, e sim pelo reconhecimento de que sua ação está em relação com a sociedade, o Estado e a família. Nesse contexto, abre-se espaço institucional e social para outras formas de responsabilização como alternativa à restrição máxima de direitos que é a privação de liberdade. Nesse primeiro encontro, nossa intenção é pautar a medida socioeducativa em meio aberto, seus desafios, limites e potencialidades. Problematizar como o meio aberto tem acolhido adolescentes em situação de violência e em conflito com a lei e como tem inventado novas formas de intervir e de conduzir um acompanhamento que afirme a liberdade e os direitos desses sujeitos.</p>', venue: "  <p>\r\n                Sala 102 da FACED <br/>\r\n                (Av. Paulo Gama s/n - Prédio 12201 térreo <br/>\r\n                Bairro Farroupilha - Porto Alegre. CEP: 90046-900) <br/>\r\n              </p>", date: "2015-04-06", start_time: "2000-01-01 18:30:00",
  speakers: meeting_one_speakers}
])
