# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Admin.create email: "saju@admin.com", password: "admin123"

About.create main_title: "COLÓQUIO", content: <<-TXT
      <p>A realiza&ccedil;&atilde;o do evento &ldquo;Col&oacute;quio Internacional de Justi&ccedil;a Juvenil na Contemporaneidade&rdquo;, no ano de 2014, resultou em uma experi&ecirc;ncia extremamente positiva no campo da socioeduca&ccedil;&atilde;o, tanto em rela&ccedil;&atilde;o &agrave;s pr&aacute;ticas profissionais, bem como na discuss&atilde;o acad&ecirc;mica.</p>\r\n\r\n
      <p>A partir dos debates e das trocas realizadas no &acirc;mbito do evento, foi poss&iacute;vel estender a interlocu&ccedil;&atilde;o entre quem vivencia, estuda ou trabalha com a tem&aacute;tica. Observamos que agentes universit&aacute;rios(as), t&eacute;cnicos(as) e professores(as) t&ecirc;m se constitu&iacute;do em importantes interlocutores e interlocutoras junto &agrave;s pessoas que operam o sistema socioeducativo, tornando-se, muitas vezes, refer&ecirc;ncia t&eacute;cnica na &aacute;rea.</p>\r\n\r\n
      <p>Todavia, h&aacute; uma necessidade de di&aacute;logo mais aprofundado entre quem trabalha cotidianamente com essa tem&aacute;tica, a qual constitui uma importante pauta pol&iacute;tica e &eacute; cotidianamente veiculada pelos meios midi&aacute;ticos e aqueles que a pesquisam e estudam. No entanto, sua abordagem ainda &eacute; bastante superficial, e n&atilde;o contempla a devida profundidade. Ainda h&aacute; muito a ser feito e discutido no campo da justi&ccedil;a juvenil.</p>\r\n\r\n
      <p>Portanto, a partir do projeto &ldquo;Col&oacute;quio Vivo&rdquo;, pretendemos seguir aprofundando o debate sobre a tem&aacute;tica e os desafios contempor&acirc;neos que envolvem a justi&ccedil;a juvenil. Por meio de trocas, experi&ecirc;ncias, debates e contribui&ccedil;&otilde;es, pretendemos, ao fim deste ciclo, disponibilizar &agrave; comunidade o resultado de trabalho desenvolvido nos encontros.</p>\r\n\r\n
      <p>Nosso p&uacute;blico-alvo abrange profissionais do Sistema Socioeducativo do Rio Grande do Sul, estudantes de Direito, Psicologia, Educa&ccedil;&atilde;o, Servi&ccedil;o Social, e todas as demais pessoas que, de alguma forma, se identifiquem com o objeto de discuss&atilde;o. Al&eacute;m de professores e de professoras universit&aacute;rias e da rede p&uacute;blica.</p>\r\n
  TXT

meeting_one_speakers = Speaker.create!([
    {name: "Carmem Maria Craidy", profile: "http://lattes.cnpq.br/3011518752311970", description: "Doutora em Educação, professora na Universidade Federal do Rio Grande do Sul e conselheira do Conselho Estadual de Educação do Estado do Rio Grande do Sul"},
    {name: "Vera Ponzio", profile: "", description: "Socióloga e Coordenadora do CREAS (Centro de Referencia Especializado de Assistência Social) Partenon"}
])

meeting_two_speakers = Speaker.create!([
    {name: "Fernanda Amador", profile: "http://lattes.cnpq.br/4367961141610735", description: "Professora do Departamento de Psicologia Social e Institucional do Instituto de Psicologia da UFRGS e líder do Grupo de Pesquisa N-PISTA(s) - Núcleo de Pesquisas em Instituições, Subjetivação e Trabalho em Análise(s)"},
    {name: "Miriam Gomes Burger", profile: "", description: "Psicóloga com formação na APPOA, experiência na área social tendo trabalhado na FASC e na FASE"}
])
meeting_three_speakers = Speaker.create!([
      {name: "Dalmir Franklin de Oliveira Junior", profile: "http://lattes.cnpq.br/7781532356800258", description: "Juiz de Direito no Juizado Regional da Infância e Juventude da Comarca de Passo Fundo"},
      {name: "Giancarlo Silkunas Vay", profile: "http://lattes.cnpq.br/3053232275125840", description: "Defensor Público do estado de São Paulo e membro do núcleo especializado da infância e juventude da DPESP (Defensoria Pública do estado de São Paulo)"}
])

meeting_four_speaker = Speaker.create!([
  {name: "Alba Maria Zaluar", profile: "http://lattes.cnpq.br/0220993427804509", description: "Antropóloga brasileira, com atuação na área de antropologia urbana e antropologia da violência. Professora aposentada do  Instituto de Medicina Social da Universidade do Estado do Rio de Janeiro, onde fundou e coordenou o Núcleo de Pesquisa em Violências (NUPEVI). Professora  visitante no Instituto de Estudos Sociais e Políticos/UERJ."}
])

Meeting.create!([
  {title: "PROCESSO PENAL JUVENIL: QUANDO A PRÁTICA OCUPA O VAZIO DA LEI", body: "<p><font><font>The effective defense of adolescents involved in illegal acts without fail permeates the defense by a democratic juvenile criminal proceedings. </font><font>Although the Statute of Children and Adolescents bring in its wake the Doctrine of Integral Protection, the device does not instrumentalized ways to ensure the effective application of this new design. </font><font>Since there are several gaps in the ECA, hermeneutics that seeks to meet them, through the application of legal operators, it shows a wide diversity, reflecting different conceptions of what is, after all, the Integral Protection. </font><font>The adoption of the civil appeal system forward to a matter that much approaches the criminal law, and legal intervention not yet solidified nature hinder the achievement of a legitimate juvenile criminal proceedings. </font><font>Experience has shown the existence of practices not consistent with adolescents&#39; rights established by the ECA. </font><font>Without a juvenile criminal proceedings that effectively guarantee the wide defense and the contradictory, the measure applied to the adolescent loses relevance. </font><font>The purpose of this panel is to discuss the judicial action on the issue, placing the participants of the symposium about the problems experienced in the practice of childhood Justice and Youth. </font><font>Finally, launches the challenge to provide alternative paths toward an effective procedural defense.</font></font></p>\r\n", venue: "                Sala 102 da FACED <br/>\r\n                (Av. Paulo Gama s/n - Prédio 12201 térreo <br/>\r\n                Bairro Farroupilha - Porto Alegre. CEP: 90046-900) <br/>\r\n", date: "2015-06-08", start_time: "2000-01-01 18:30:00",
  speakers: meeting_three_speakers },
  {title: "QUEM CUIDA DA SAÚDE DE QUEM TRABALHA NA SOCIOEDUCAÇÃO?", body: "<p><font><font>The number of people working in the National Socio-Educational Services System - SINASE has increased across the country each year, both in the sphere of management of the institutions and in the implementation of the policy. </font><font>According to Costa et al (2014), can not run educational measures, according to the normative content of SINASE in addition to human resources, prepared, involved and motivated for this task, which brings content that directly affect the subjectivity of the worker. </font><font>The SINASE while public policy has become an area of ​​services whose main mediation is (a) own (a) worker (a), (s) he is its core technology, so the job requires, and new forms of regulation, organization and management, look and take care of this target audience. </font><font>Our proposal for this meeting is to discuss and debate how we are taking up the challenge of caring for those working in the socio-educational.</font></font></p>\r\n", venue: "<p>Sala 102 da FACED <br/>\r\n      (Av. Paulo Gama s/n - Prédio 12201 térreo <br/>\r\n      Bairro Farroupilha - Porto Alegre. CEP: 90046-900)<br/>\r\n</p>", date: "2015-05-25", start_time: "2000-01-01 18:30:00",
  speakers: meeting_two_speakers },
  {title: "IDENTIDADE MASCULINA E VIOLÊNCIA: DISCUTINDO GÊNERO NA MORTALIDADE JUVENIL", body: "<p>De acordo com a perspectiva e estudo sobre as quest&otilde;es de g&ecirc;nero, mulheres e homens vivem, exercem e percebem a viol&ecirc;ncia e a inseguran&ccedil;a de maneira diferente, assim como seu impacto &eacute; diferente em um ou outro g&ecirc;nero. Diversos estudos apontam que a taxa de homic&iacute;dios de v&iacute;timas do sexo masculino com idades ente 15 e 29 anos na Am&eacute;rica do Sul &eacute; uma das maiores do mundo. Pode-se considerar que a concentra&ccedil;&atilde;o de viol&ecirc;ncia neste grupo est&aacute; relacionada com a preval&ecirc;ncia de padr&otilde;es socioculturais, formas de socializa&ccedil;&atilde;o e identifica&ccedil;&atilde;o subjetivantes que contribuem para que valores como o respeito, a dignidade e o reconhecimento dos pares estejam associados, na pr&aacute;tica, com a disposi&ccedil;&atilde;o a adotar condutas e formas de conviv&ecirc;ncia violentas. Por tal motivo, buscamos, neste encontro, problematizar a constru&ccedil;&atilde;o social de masculinidades permeadas pela viol&ecirc;ncia, na tentativa de auxiliar a compreens&atilde;o das implica&ccedil;&otilde;es de tal fen&ocirc;meno nas vidas/experi&ecirc;ncias de adolescentes em conflito com a lei.</p>\r\n", venue: "              <p>\r\n                Sala 102 da FACED <br/>\r\n                (Av. Paulo Gama s/n - Prédio 12201 térreo <br/>\r\n                Bairro Farroupilha - Porto Alegre. CEP: 90046-900) <br/>\r\n              </p>\r\n", date: "2015-07-06", start_time: "2000-01-01 18:30:00",
  speakers: meeting_four_speaker },
  {title: "MEDIDAS SOCIOEDUCATIVAS EM MEIO ABERTO: O EXERCÍCIO DA RESPONSABILIZAÇÃO COM LIBERDADE", body: "<p><font><font>The discussion of socio-educational measures in Rio Grande do Sul and Brazil shows no uniformity with regard to their place of education, socialization and accountability. </font><font>We note that the expectation on the punishment of those who are &quot;in conflict with the law&quot;, to society in general, has always been that the punishment infringed to (the) criminal (a) - in the case of teenagers, those ( as) who practice offense - was big enough and severe enough to end the recurrence. </font><font>The proposition of an accountability system that prioritizes people over the offense, is the big difference between the Criminal Code and provides that the Statute of Children and Adolescents. </font><font>There is a counterpoint that is effective in socio-educational measures of an open environment because it is not an isolated person who should answer for their conduct alone, but by recognizing that their action is in relation to society, the state and the family. </font><font>In this context, open up institutional and social space for other forms of accountability as an alternative to maximum restriction of rights is deprivation of liberty. </font><font>In that first meeting, our intention is to guide the socio-educational measures in an open environment, its challenges, limitations and potential. </font><font>Discuss how the open system has hosted adolescents in situations of violence and conflict with the law and how it has invented new ways to intervene and conduct a follow-up that affirms the freedom and rights of these individuals.</font></font></p>\r\n\r\n<p>&nbsp;</p>\r\n", venue: "  <p>\r\n                Sala 102 da FACED <br/>\r\n                (Av. Paulo Gama s/n - Prédio 12201 térreo <br/>\r\n                Bairro Farroupilha - Porto Alegre. CEP: 90046-900) <br/>\r\n              </p>", date: "2015-04-06", start_time: "2000-01-01 18:30:00",
  speakers: meeting_one_speakers}
])
